spring:
  datasource:
    url: jdbc:h2:mem:todo-list
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.properties.hibernate.jdbc.time_zone: UTC
  jackson:
    spring.jackson.serialization.write_dates_as_timestamps: false
  h2:
    spring.h2.console.enabled: true
    spring.h2.console.path: /h2-console

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}